---
name: build-docker

on:
  workflow_dispatch:
  push:
    branches:
      - main_elty
      - staging
  pull_request:
    branches:
      - feature-sc-*
      - master
      - staging
      - feature-sc-62683-formbricks-github-workflow-for-create-and # Temp add for testing purposes
  release:
    types: [released]

concurrency:
  group: formbricks-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
    name: formbricks
    runs-on: github-action-runner-scale-set-docker
    outputs:
      DOCKER_TAG: ${{ steps.extract_branch.outputs.DOCKER_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud and docker
        uses: ./.github/actions/set-up-gcloud-and-docker
        with:
          google-credentials: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Extract branch name
        run: |-
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            SHORT_SHA=$(echo "${{github.event.pull_request.head.sha}}" | cut -c1-8)
            echo "DOCKER_TAG=pr-${{github.event.number}}-$SHORT_SHA" >> $GITHUB_OUTPUT
          elif [ ${{ github.event_name }} == 'push' ]; then
            echo "DOCKER_TAG=${{ GITHUB.SHA }}-$GITHUB_REF_NAME-latest" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == 'release' ]; then
            RELEASE_VERSION=${{ github.event.release.tag_name }}
            VERSION=${RELEASE_VERSION##*@}
            echo "DOCKER_TAG=${VERSION}-release" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            SHORT_SHA=$(echo "${{github.sha}}" | cut -c1-8)
            echo "DOCKER_TAG=${SHORT_SHA}-manual" >> $GITHUB_OUTPUT
          fi
        id: extract_branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push formbricks
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'europe-west8-docker.pkg.dev/common-project-bd8c/common-repo/formbricks:${{ steps.extract_branch.outputs.DOCKER_TAG }}'
          file: ./apps/web/Dockerfile